from typing import Protocol
class EstablishmentRepository(Protocol):
    async def get(self, entity_id): ...
class ActionRepository(Protocol):
    async def get(self, entity_id): ...
class ArticleRepository(Protocol):
    async def find_duplicate(self, canonical_url, content_hash): ...
class ReviewRepository(Protocol):
    async def get_by_token_hash(self, token_hash): ...
class UnitOfWork(Protocol):
    async def commit(self): ...
    async def rollback(self): ...

