import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useLocation} from 'react-router-dom';
import EnforcementMap from '../components/Map/EnforcementMap';
import Search from '../components/Search/Search';
import ThemeToggle from '../components/ThemeToggle';
import {getMapEstablishments,getOverview} from '../services/api';

function Brand(){return <div className="brand" aria-label="Tukaram Maps"><span className="brandMark">TM</span><span><b>TUKARAM MAPS</b><small>Verified Enforcement Actions</small></span></div>}
function Legend(){return <div className="legend" aria-label="Map status legend"><span><i className="blue"/>Action Taken</span><span><i className="amber"/>Warning / Notice</span><span><i className="red"/>Licence Suspended</span><span><i className="green"/>Open / Operating</span></div>}
function Overview(){const {data}=useQuery({queryKey:['overview'],queryFn:getOverview});return <aside className="overview"><h3>Overview <span>(All India)</span></h3><p><i className="blue"/>Action Taken <b>{data?.actions??'—'}</b></p><p><i className="amber"/>Warning / Notice <b>{data?.warnings??'—'}</b></p><p><i className="red"/>Licence Suspended <b>{data?.suspended??'—'}</b></p><p><i className="green"/>Open / Operating <b>{data?.open??'—'}</b></p></aside>}
function DetailPanel({item,onClose}){if(!item)return null;const action=item.latest_action||{};const actionName=(action.type||'ACTION TAKEN').replaceAll('_',' '),status=(item.current_status||'UNKNOWN').replaceAll('_',' '),isOpen=item.current_status==='OPEN',directions=`https://www.google.com/maps/dir/?api=1&destination=${item.latitude},${item.longitude}`;return <aside className="detailsPanel" aria-label="Establishment details"><div className="panelTools"><span className="statusPill">{actionName}</span><span><button aria-label="Bookmark">♡</button><button onClick={onClose} aria-label="Close details">×</button></span></div><h2>{item.name} <em title="Verified historical action">✓</em></h2><p className="location">⌖ {item.city}, {item.state}</p><p className="operating"><i className={isOpen?'green':'amber'}/> Current status: {status}</p><div className="infoGrid"><div><small>Establishment Type</small><b>{item.type?.replaceAll('_',' ')||'Hospitality'}</b></div><div><small>Inspected By</small><b>{action.authority||'Verified authority'}</b></div><div><small>Date of Action</small><b>{action.date||'Not reported'}</b></div><div><small>Action</small><b>{actionName}</b></div></div><div className="statusCards"><div><small>Current Status</small><b><i className={isOpen?'green':'amber'}/> {status}</b></div><div><small>Evidence</small><b>Verified historical record</b></div></div><h3>Action History</h3><div className="actionTimeline"><article><i/><small>{action.date||'Date not reported'}</small><b>{actionName}</b><p>{action.reason||'Enforcement action verified against linked public evidence.'}</p></article></div><a className="primaryAction" href={`/establishments/${item.id}`}>View Full Details</a><a className="secondaryAction" href={directions} target="_blank" rel="noreferrer">Get Directions</a><footer>Source: verified public evidence <span>Current status shown separately</span></footer></aside>}
export default function Home(){const location=useLocation(),initialFocus=location.state?.focus||null;const [viewport,setViewport]=useState(null),[focus,setFocus]=useState(initialFocus),[selected,setSelected]=useState(initialFocus);const params={...viewport};const {data=[],isLoading,error}=useQuery({queryKey:['map',params],queryFn:()=>getMapEstablishments(params),enabled:!!viewport});const handleSearchSelect=item=>{setFocus(item);setSelected(item.kind==='state'||item.kind==='city'?null:item)};return <main className="mapPage"><Brand/><div className="topSearch"><Search onSelect={handleSearchSelect}/></div><Legend/><ThemeToggle/><section className="mapShell">{isLoading&&<div className="notice">Loading map data…</div>}{error&&<div className="notice error">Unable to load map data.</div>}{!isLoading&&!error&&viewport&&!data.length&&<div className="notice">No verified establishments found.</div>}<EnforcementMap items={data} onViewport={setViewport} focus={focus} onSelect={setSelected}/></section><Overview/><DetailPanel item={selected} onClose={()=>setSelected(null)}/></main>}
