from enum import StrEnum
class EstablishmentType(StrEnum): RESTAURANT="RESTAURANT"; HOTEL="HOTEL"
class CurrentStatus(StrEnum): OPEN="OPEN"; CLOSED="CLOSED"; UNKNOWN="UNKNOWN"
class ActionType(StrEnum):
    SEALED="SEALED"; FINED="FINED"; RAIDED="RAIDED"; NOTICE_ISSUED="NOTICE_ISSUED"; LICENSE_CANCELLED="LICENSE_CANCELLED"; SHUT_DOWN="SHUT_DOWN"; DEMOLISHED="DEMOLISHED"; REOPENED="REOPENED"; OTHER="OTHER"
class ActionStatus(StrEnum): PENDING_REVIEW="PENDING_REVIEW"; APPROVED="APPROVED"; REJECTED="REJECTED"
class SourceType(StrEnum): NEWS="NEWS"; GOVERNMENT="GOVERNMENT"; OFFICIAL_NOTICE="OFFICIAL_NOTICE"; OTHER="OTHER"
class ReviewStatus(StrEnum): PENDING="PENDING"; APPROVED="APPROVED"; REJECTED="REJECTED"; EXPIRED="EXPIRED"

